### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by fjp** [jdoiro3/mkdocs-multirepo-plugin#15]
Hi, after updating from release 0.3.2 to 0.3.3 I get the following error when I try to run `mkdocs build`:

```
File "C:\Users\fjp\dev\documentation-mkdocs\venv\lib\site-packages\mkdocs_multirepo_plugin\structure.py", line 68, in get_import_stmts
    (section, value), = entry.items()
AttributeError: 'str' object has no attribute 'items'
```

When I use 0.3.2 the building and serving works without errors. Nothing changed in my mkdocs.yml. Is there anything that I should update on my side?

**Comment by fjp** [comment]
I think the issue is caused by having the following configuration using the [`navigation.indexes`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages) feature from the material theme.

The following config results in the error mentioned above:

```yml
site_name: Test

plugins:
  - multirepo

nav:
  - Home:
    - index.md     # This uses the navigation.indexes feature from material mkdocs
    - About: about.md    
  - MicroService: '!import https://github.com/…'
```

Changing the `nav` section to the following gets rid of this error:

```yml
nav:
  - Home:
    - Home: index.md
    - About: about.md
  - Statechart_Generator: '!import git@github.hexagon.com:geo-surv/tls-tools-statechart-generator.git'
```

**Comment by jdoiro3** [comment]
@fjp thanks for providing the additional context. It definitely helped me fix this bug. Version `0.3.4` should have fixed this.

```
Running E2E tests via Bats in Docker (python:3.7-slim) -------->
  ✓ builds a mkdocs site with repos section 
  ✓ builds a mkdocs site with nav section 
 ✅ builds a mkdocs site with nav section using material's indexes nav
  ✓ builds a mkdocs site with a different config file name and location 
  ✓ builds a mkdocs site with multiple imports in nav section 
  ✓ Make sure imported repo's mkdocs.yml isn't in build output 

6 tests, 0 failures
```
